// Implemented the Real-Time Market Analysis flow using Genkit.
'use server';
/**
 * @fileOverview Fetches real-time market data, analyzes trends using the Gemini model, and provides actionable insights.
 *
 * - analyzeMarket - A function that handles the market analysis process.
 * - AnalyzeMarketInput - The input type for the analyzeMarket function.
 * - AnalyzeMarketOutput - The return type for the analyzeMarket function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeMarketInputSchema = z.object({
  crop: z.string().describe('The crop to analyze.'),
  language: z.string().describe('The language to respond in.'),
});
export type AnalyzeMarketInput = z.infer<typeof AnalyzeMarketInputSchema>;

// This schema defines the structure of the market analysis data that will be returned to the user.
// It includes the summary generated by the AI.
const MarketDataSchema = z.object({
  price: z.number().describe('The current price of the crop.'),
  trend: z.string().describe('The current market trend (e.g., increasing, decreasing, stable).'),
  summary: z.string().describe('A short, actionable summary of the market situation and selling advice.'),
});

const AnalyzeMarketOutputSchema = z.object({
  marketAnalysis: MarketDataSchema.describe('The market analysis for the specified crop.'),
});
export type AnalyzeMarketOutput = z.infer<typeof AnalyzeMarketOutputSchema>;

export async function analyzeMarket(input: AnalyzeMarketInput): Promise<AnalyzeMarketOutput> {
  return analyzeMarketFlow(input);
}

// This schema defines the output of our data-fetching tool. It only contains raw data.
const MarketDataToolSchema = z.object({
    price: z.number().describe('The current price of the crop.'),
    trend: z.string().describe('The current market trend (e.g., increasing, decreasing, stable).'),
});


const getMarketData = ai.defineTool({
  name: 'getMarketData',
  description: 'Fetches real-time market data for a specific crop.',
  inputSchema: z.object({
    crop: z.string().describe('The crop to fetch market data for.'),
  }),
  outputSchema: MarketDataToolSchema,
}, async (input) => {
  // This is a placeholder implementation that simulates fetching real-time market data from a public API.
  console.log(`Fetching market data for ${input.crop}`);

  const mockMarketData: { [key: string]: { price: number; trend: string; } } = {
    'tomatoes': { price: 50, trend: 'increasing' },
    'wheat': { price: 20, trend: 'stable' },
    'potatoes': { price: 30, trend: 'decreasing' },
    'corn': { price: 15, trend: 'stable' },
    'rice': { price: 40, trend: 'increasing' },
    'onions': { price: 25, trend: 'stable' },
  };

  const cropKey = input.crop.toLowerCase();
  const data = mockMarketData[cropKey];

  if (data) {
    return {
      price: data.price,
      trend: data.trend,
    };
  }

  // Fallback for crops not in the mock data
  const randomPrice = Math.floor(Math.random() * 100) + 10;
  const randomTrend = ['increasing', 'decreasing', 'stable'][Math.floor(Math.random() * 3)] as 'increasing' | 'decreasing' | 'stable';
  return {
    price: randomPrice,
    trend: randomTrend,
  };
});

const prompt = ai.definePrompt({
  name: 'analyzeMarketPrompt',
  input: {schema: AnalyzeMarketInputSchema},
  output: {schema: AnalyzeMarketOutputSchema},
  tools: [getMarketData],
  prompt: `You are an expert market analyst for farmers.

  A farmer is asking about the price of {{crop}} in their local language, which is {{language}}. The prices provided by the tool are in Indian Rupees (INR) per kg.

  First, use the getMarketData tool to get the current market data for the specified crop.

  Then, based on the data you receive from the tool, provide a simple, actionable summary of the market trends to guide the farmer's selling decisions. This summary should be in the farmer's specified language and mention the price in Rupees. The summary should be helpful and give advice, for example, if the trend is 'increasing', you might advise them to wait a bit before selling.

  Finally, populate all the fields in the output schema, including the price, trend, and the summary you generated.
`,
});

const analyzeMarketFlow = ai.defineFlow(
  {
    name: 'analyzeMarketFlow',
    inputSchema: AnalyzeMarketInputSchema,
    outputSchema: AnalyzeMarketOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
